app/models.py
from . import db


class Essay(db.Model):
    __tablename__ = 'essays'
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.Text)
    time = db.Column(db.DateTime(True))
    score = db.Column(db.Float)
    spell_errors = db.Column(db.Text)
    grammar_errors = db.Column(db.Text)
    coherence = db.Column(db.Text)

    def __repr__(self):
        return u'<Essay {0}>: {1}. Created at:{2}'.format(self.id, self.score,
                                                          self.time)

app/main/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import Required, Length


class EssayForm(Form):
    essay = TextAreaField('Please input your essay.',
                          validators=[Required(), Length(min=2)])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.sqlalchemy import SQLAlchemy
from config import config

bootstrap = Bootstrap()
db = SQLAlchemy()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    db.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
import json
from datetime import datetime

from flask import (render_template, session, redirect, url_for, current_app,
                   flash)
from .. import db
from ..models import Essay
from . import main
from .forms import EssayForm
from ..scoring import EssayScorer


@main.route('/', methods=['GET', 'POST'])
def index():
    form = EssayForm()
    if form.validate_on_submit():
        text = form.essay.data
        time = datetime.now()
        es = EssayScorer(text)
        score, spell_e, gram_e, coh = (es.score, es.spell_errors,
                                       es.grammar_errors, es.coherence)
        essay_tuple = Essay(text=text,
                            time=time,
                            score=score,
                            spell_errors=json.dumps(spell_e),
                            grammar_errors=json.dumps(gram_e),
                            coherence=json.dumps(coh))
        db.session.add(essay_tuple)

        flash('Your essay is scored. You got point {} of 6.'.format(score))
        flash('Your essay\'s coherence: {}'.format(coh))
        return render_template('result.html', text=text, es=es, zip=zip)
    return render_template('index.html', form=form)


@main.route('/about', methods=['GET'])
def about():
    return render_template('about.html')

app/templates/about.html
{% extends "base.html" %}

{% block page_content %}
<div class="page-header">
    <div class="container-fluid">
    	<div class="row-fluid">
    		<div class="span12 lead">
    			<p>
    				<em>Essai</em> is a English essay scoring web application. Features are:
    			</p>
    			<ul>
    				<li>
    					A holistic score from 1 to 6 (greater means better)
    				</li>
    				<li>
    					Spell checking and grammar checking
    				</li>
    				<li>
    					Coherence feedback
    				</li>
    			</ul>
    			<p>
    				If you use this web application, please do <strong>NOT</strong> submit any confidential documents, although we don't keep your documents permanently by periodically clearing the database.
    			</p>
    		</div>
    	</div>
    </div>
</div>
{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block html_attribs %} lang="en" {% endblock %}

{% block title %}Essai - Score your English essay.{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='icon.png') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='icon.png') }}" type="image/x-icon">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/flat-ui/2.2.2/css/flat-ui.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='css/customize.css') }}">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Essai</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
                <li><a href="{{ url_for('main.about') }}">About</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container" style="padding-bottom:120px;">

  {% for message in get_flashed_messages() %}
  <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      {{ message }}
  </div>
  {% endfor %}

  {% block page_content %}{% endblock %}
</div>

<footer class="footer" style="background:#384452;color:#BFC9D3">
  <div class="container">
    <div class="row">
      <div class="col-xs-8">
        <h6>
          <small>This application is powered by <a href="http://flask.pocoo.org/">Flask</a>
          and <a href="http://designmodo.github.io/Flat-UI/">Flat UI</a>.</small>
        </h6>
      </div>
      <div class="col-xs-4">
        <h6>
          <small>Contact me at:
            <span class=fui-github></span> <a href="https://github.com/kigawas">GitHub</a>
            <span> & </span>
            <span class="fui-twitter"></span> <a href="https://twitter.com/kigawas">Twitter</a>
          </small>
        </h6>
      </div>
    </div>
  </div>
</footer>

{% endblock %}



{% block scripts %}
{{ super() }}
{% endblock %}

app/templates/index.html
{% import "bootstrap/wtf.html" as wtf %}

{% extends "base.html" %}


{% block page_content %}

<div class="page-header">
    <h2>Welcome to essai!</h2>
</div>
{{ wtf.quick_form(form)}}
{% endblock %}

app/templates/result.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}

<div class="row">
  <div class="col-xs-3">
    <div class="input-group">
    	<input type="text" class="form-control" placeholder="{{ es.score }}">
      <span class="input-group-btn">
        <button class="btn btn-success" type="button">OK</button>
      </span>
    </div>
  </div>
  <div class="col-xs-3">
    <div class="input-group">
      <input type="text" class="form-control" placeholder="{{ es.coherence }}">
      <span class="input-group-btn">
        <button class="btn btn-success" type="button">OK</button>
      </span>
    </div>
  </div>
</div>

<div class="page-header">
	<h2>Result</h2>
</div>



<div class="container-fluid">
	{% for sent, sp_e, gr_e in zip(es.sents, es.spell_errors.itervalues(), es.grammar_errors.itervalues()) %}
	<div class="row-fluid row-eq-height">
		<div class="col-md-6">
			<ul class="list-group">
				<div class="list-group-item">
					<div class="list-group-item-heading">{{ sent }}</div>
				</div>
			</ul>
		</div>

		<div class="col-md-6">
			<ul class="list-group">
				<li class="list-group-item">
					{% for em in gr_e %}
							<strong class="list-group-item-heading" >{{  "'{}' may be a grammar error.".format(sent[em.fromx:em.tox]) }} </strong>
							<p class="list-group-item-text">{{ em.msg }}</p>
					{% else %}
							<p class="list-group-item-text">No detected grammar errors.</p>
					{% endfor %}
				</li>
				<li class="list-group-item">
					{% for e in sp_e %}
						{% for wrong, correct in e.iteritems() %}
							<strong class="list-group-item-heading" >{{  "'{}' may be a spell error.".format(wrong) }} </strong>
							<p class="list-group-item-text">{{ "You may want to use '{}' or '{}'.".format(correct[0], correct[1]) }} </p>
						{% endfor %}
					{% else %}
						<p class="list-group-item-text">No detected spell errors.</p>
					{% endfor %}
				</li>
			</ul>
		</div>

	</div>
	{% endfor %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script type="text/javascript">
	tinymce.init({ /* global tinymce */
	  selector: '.myeditablediv',
	  menubar:false,

    toolbar: "forecolor backcolor searchreplace",
    statusbar: false,
    inline: true,
    plugins: "noneditable textcolor searchreplace"
	});
</script>
{% endblock %}